name: Publish Package to npmjs or GitHub Packages

on:
  release:
    types: [published] # Trigger when a release is published
  workflow_dispatch: # Allow manual triggering for dry runs

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      # - run: npm test

  # github-dry-run:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         registry-url: 'https://npm.pkg.github.com'
  #         scope: '@kyletaylored'
  #         cache: 'npm'
  #     - name: Verify GitHub Packages Authentication
  #       run: cat $NPM_CONFIG_USERCONFIG && npm whoami
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Simulate GitHub Packages Publish
  #       run: npm ci && npm pack --dry-run

  # github-publish:
  #   if: github.event_name == 'release'
  #   needs: github-dry-run
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         registry-url: 'https://npm.pkg.github.com'
  #         scope: '@kyletaylored'
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm publish --provenance
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-dry-run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - name: Verify npm Authentication
        run: cat $NPM_CONFIG_USERCONFIG && npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Simulate npm Publish
        run: npm ci && npm pack --dry-run

  npm-publish:
    if: github.event_name == 'release'
    needs: npm-dry-run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
